[package]
name = "tasktracker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.17"
askama = "0.11"
serde = "1.0.147"
tokio = { version = "1.0", features = ["full"] }